# Python_Challenge
Fixed some issues but not all, I will live with it.
